### PR TITLE
feat: create UI components floating action button

### LINKED ISSUE #13: Create UI components `floating action button`
## Description

- The task is to create a shared UI component for a `floating action button`.

## Criteria

- [ ] create a `floating action button` component

## Notes

image

## Assignment 

|Role|Assignee |
|---|---|
|`Developer`|@Akikaze1119 |
|`Reviewer`| @akiomatic |

### PR DESCRIPTION
**Pull request by Akikaze1119**
## Overview
The task is to create a shared UI component for `floating action button`.

## Changes
Created `floating action button` component with `Button` component and styled it based on [figma](https://www.figma.com/file/5tNJDDfqC0HnHbWygzEXiL/Tascurator?type=design&node-id=0-1&mode=design&t=SvzFH1RdR9OWCQRn-0)
 
## Screenshots or videos
▼Figma
image

▼Code
https://github.com/Tascurator/tascurator-frontend/assets/132441773/aeb0ac5d-7c1a-45ca-ac76-c545a0d8b554

### About Shadows
I'm using TailWindCSS `shadow-md` instead of the style as per Figma.

▼ Reasons for change
(1) Basically, because of the policy of using TailWindCSS class for production.
(2) Because I think that shadow-md is able to express a concave image sufficiently.

## Assignee Checklist:

- [x] The base branch is correct (no accidental merges)
- [x] The branch name follows our branch naming rules
- [x] The PR title follows our PR title rules
- [x] My code follows our coding style
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors in the console

## Reviewer Checklist:

- [x] Code readability and simplicity
- [x] Follows best practices and coding standards
- [x] Understandable and maintainable code

### CODE REVIEW

**Review by akiomatic — CHANGES_REQUESTED** [review]
Could you modify the PR title to match our standard?

**Comment by Akikaze1119** [comment]
> Could you modify the PR title to match our standard?

Thank you for your review.
Sorry, I modified it.

Feature/13 create UI components floating action button
↓
feat/13 create UI components floating action button

**Comment by akiomatic** [comment]
> > Could you modify the PR title to match our standard?
> 
> Thank you for your review. Sorry, I modified it.
> 
> Feature/13 create UI components floating action button ↓ feat/13 create UI components floating action button

The PR title is still not currently following our standards. Just like the [commit message guidlines](https://github.com/Tascurator/tascurator-frontend/blob/develop/CONTRIBUTING.md#commit-message-guidelines), the PR title should follow the format: `type(optional scope): description`.

**Comment by Akikaze1119** [comment]
> The PR title is still not currently following our standards. Just like the [commit message guidlines](https://github.com/Tascurator/tascurator-frontend/blob/develop/CONTRIBUTING.md#commit-message-guidelines), the PR title should follow the format: `type(optional scope): description`.

 Sorry, I missed to modify `/` ⇨ `:`
 I modified it.

**Comment by akiomatic** [comment]
> > The PR title is still not currently following our standards. Just like the [commit message guidlines](https://github.com/Tascurator/tascurator-frontend/blob/develop/CONTRIBUTING.md#commit-message-guidelines), the PR title should follow the format: `type(optional scope): description`.
> 
> Sorry, I missed to modify `/` ⇨ `:` I modified it.

Could you please adjust the title to start with `verb` like `feat: (verb) (noun)`?

**Comment by Akikaze1119** [comment]
> > > The PR title is still not currently following our standards. Just like the [commit message guidlines](https://github.com/Tascurator/tascurator-frontend/blob/develop/CONTRIBUTING.md#commit-message-guidelines), the PR title should follow the format: `type(optional scope): description`.
> > 
> > 
> > Sorry, I missed to modify `/` ⇨ `:` I modified it.
> 
> Could you please adjust the title to start with `verb` like `feat: (verb) (noun)`?

I remove number.

**Review by akiomatic — APPROVED** [review]
LGTM.

**Pull request merged**
