### PR TITLE
feat: install Next.js

### LINKED ISSUE #3: Install Next.js
## Description

This issue aims to install and initialize Next.js 14 by running `npx create-next-app@latest` to create the codebase for this application.

## Criteria

- [x] Install Next.js 14 in the root folder
- [x] Install ESLint
- [x] Install Tailwind CSS
- [x] Use `src/` directory
- [x] Use App Router
- [x] Do not customize the default import alias

## Notes

- For your reference, this is the official documentation on how to install Next.js: https://nextjs.org/docs/getting-started/installation
- If some existing files prevented Next.js from initializing in the root folder, the assignee might need to temporarily delete those files in a backup folder and move them back after finishing the initialization.

### PR DESCRIPTION
**Pull request by KaiKoide**
## Overview

Install Next.js, which is necessary for this application, and proceed with development along with ESLint and Tailwind CSS. Other configurations were made during installation as follows.

## Changes

- [x] Install Next.js 14 in the folder
  - [x] Install ESLint
  - [x] Install Tailwind CSS
  - [x] Use `src/` directory
  - [x] Use App Router
  - [x] Do not customize the default import alias

## Assignee Checklist:

- [x] The base branch is correct (no accidental merges)
- [x] The branch name follows our branch naming rules
- [x] The PR title follows our PR title rules
- [x] My code follows our coding style
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors in the console

## Reviewer Checklist

- [x] Install Next.js 14 correctly

### CODE REVIEW

**Comment by akiomatic** [comment]
Hi. Thank you for your PR, but could you update the description as it is just a copy and paste from the issue and my previous PR.

**Comment by KaiKoide** [comment]
> Hi. Thank you for your PR, but could you update the description as it is just a copy and paste from the issue and my previous PR.

Thank you for your review!
I modified my PR.

**Review by akiomatic — APPROVED** [review]
I've just confirmed your setup is done correctly.
Thank you!

**Review by yuki-92c — APPROVED** [review]
Thank you Kai:)

**Review by HrRn — APPROVED** [review]
Thank you!

**Comment by Akikaze1119** [comment]
Thanks for your work!

**Review by Akikaze1119 — APPROVED** [review]

**Pull request merged**
