### PR TITLE
fix: change name to shared house

### LINKED ISSUE #373: Change name to shared house
## Description

Since "share house" is not accurate in English, change "share house" to "shared house" on the screen.

### PR DESCRIPTION
**Pull request by KaiKoide**
## Overview

Since "share house" is not accurate in English, change "share house" to "shared house" on the screen.

## Changes

- Change the name on the dropdown menus
- Change the name on the drawers
- Change the name in the new shared house creation page
- Change the name on the dashboard page

## Screenshots or videos

**dropdown menus**
image
</p>

**drawers**
<p>
image
image
</p>

**dashboard page**
image

**new shared house creation page**
<p>
image
image
image
image
</p>

## Assignee Checklist:

- [ ] The base branch is correct (no accidental merges)
- [ ] The branch name follows our branch naming rules
- [ ] The PR title follows our PR title rules
- [ ] My code follows our coding style
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors in the console

## Reviewer Checklist:

- [ ] Code readability and simplicity
- [ ] Follows best practices and coding standards
- [ ] Understandable and maintainable code

### CODE REVIEW

**Review by akiomatic — CHANGES_REQUESTED** [review]
I found that error messages in the backend do not have changed to `shared house`, so could you please fix them?

Examples:
image

**Review by akiomatic — CHANGES_REQUESTED** [review]
I've found 1 other file that still has the word "share house",  so could you fix it?

https://github.com/Tascurator/tascurator-frontend/blob/89a08da7312946499672dd9c5223cda62991f4e4/src/constants/input-texts.ts#L24

**Comment by KaiKoide** [comment]
> I've found 1 other file that still has the word "share house", so could you fix it?
> 
> https://github.com/Tascurator/tascurator-frontend/blob/89a08da7312946499672dd9c5223cda62991f4e4/src/constants/input-texts.ts#L24

@akiomatic 
Thank you for your review! I fixed that!

**Review by akiomatic — APPROVED** [review]
Thank you. LGTM.

**Pull request merged**
