### PR TITLE
docs: add issue/PR templates & `CONTRIBUTING.md`

### LINKED ISSUE #1: Create issue/PR templates and `CONTRIBUTING.md`

### PR DESCRIPTION
**Pull request by akiomatic**
## Overview

This PR introduces 2 issue templates for new tasks and reporting problems, and `CONTRIBUTING.md` for guidelines.

## Changes

- Added [CONTRIBUTING.md](https://github.com/Tascurator/tascurator/blob/docs/1-create-issuepr-templates-and-contributingmd/CONTRIBUTING.md)
- Created `.github` directory
- Added [pull_request_template.md](https://github.com/Tascurator/tascurator/blob/fd1602e133fd23988330f2dfec34c4f21f481f93/.github/pull_request_template.md) in `.github/`
- Added [task.md](https://github.com/Tascurator/tascurator/blob/fd1602e133fd23988330f2dfec34c4f21f481f93/.github/ISSUE_TEMPLATE/task.md) and [problem.md](https://github.com/Tascurator/tascurator/blob/fd1602e133fd23988330f2dfec34c4f21f481f93/.github/ISSUE_TEMPLATE/problem.md) in `.github/ISSUE_TEMPLATE/`

## Review points

- I'd like the reviewers to check there are no English language errors.
- Are the documentation and templates easy to understand?
- I'm not 100% confident with the `Assignee Checklist` and `Reviewer Checklist` in [pull_request_template.md](https://github.com/Tascurator/tascurator/blob/fd1602e133fd23988330f2dfec34c4f21f481f93/.github/pull_request_template.md).

## Assignee Checklist:

- [x] The base branch is correct (no accidental merges)
- [x] The branch name follows our branch naming rules
- [x] The PR title follows our PR title rules
- [x] My code follows our coding style
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors in the console

## Reviewer Checklist

- [ ] Code readability and simplicity
- [ ] Follows best practices and coding standards
- [ ] Understandable and maintainable code

### CODE REVIEW

**Comment by KaiKoide** [comment]
What are `task` and `problem` in `.github/ISSUE_TEMPLATE/` used for?

**Comment by akiomatic** [comment]
> What are `task` and `problem` in `.github/ISSUE_TEMPLATE/` used for?
@KaiKoide 

Thank you for pointing it out.
These are issue templates that have different purposes. The one, `task`, is designed to create issues for new tasks. On the other hand, the `problem` is to report issues, bugs, or problems in this application, which need to be fixed later.

**Comment by KaiKoide** [comment]
> > What are `task` and `problem` in `.github/ISSUE_TEMPLATE/` used for?
> > @KaiKoide
> 
> Thank you for pointing it out. These are issue templates that have different purposes. The one, `task`, is designed to create issues for new tasks. On the other hand, the `problem` is to report issues, bugs, or problems in this application, which need to be fixed later.

Thank you for your explanation! LGTM:)

**Review by KaiKoide — APPROVED** [review]

**Review by HrRn — APPROVED** [review]
Thank you!

**Review by yuki-92c — APPROVED** [review]
Thanks! LGTM:)

**Review by Akikaze1119 — APPROVED** [review]
Thank you! LGTM!!

**Pull request merged**
