### PR TITLE
feat: modify spacing and overflow in the `DrawerDescription` component

### LINKED ISSUE #131: Fix spacing and overflow in the `DrawerDescription` component
## Description
In this task, I'd like to make two changes to the `DrawerDescription` component. Firstly, modify the padding to improve spacing around the content. Secondly, make it scrollable vertically when its content overflows.

## Criteria

- [x] Modify the padding in the `DrawerDescription` component
- [x] Support overflowing the content of the `DrawerDescription` component

### PR DESCRIPTION
**Pull request by akiomatic**
## Overview

I've adjusted the `DrawerDescription` component to enhance its usability when content overflows. Specifically, I've made the component scrollable and refined the spacing by replacing y-axis paddings with margins for better visual separation during scrolling.

## Changes

- Made the `DrawerDescription` scrollable by setting height and overflow classes
- Changed the y-axis paddings with margins 
- Added `break-words` and `text-wrap` for extremely long words

## Screenshots or videos

https://github.com/Tascurator/tascurator-frontend/assets/124953279/5587a190-87db-461a-9a75-463781ef50cf

## Assignee Checklist:

- [x] The base branch is correct (no accidental merges)
- [x] The branch name follows our branch naming rules
- [x] The PR title follows our PR title rules
- [x] My code follows our coding style
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors in the console

## Reviewer Checklist:

- [ ] Code readability and simplicity
- [ ] Follows best practices and coding standards
- [ ] Understandable and maintainable code

### CODE REVIEW

**Review by yuki-92c — COMMENTED** [review]
Thank you! 
Can I ask how to check the scroll feature? In my environment, I cannot check it. I use the code below.

```ts
      <Drawer>
        <DrawerTrigger asChild>
          <Button>Open Drawer</Button>
        </DrawerTrigger>
        <DrawerContent>
          <DrawerTitle>Login</DrawerTitle>
          <DrawerDescription>
            aaaa hausidfhauisdhfui uahsdfuiasshfuisudf huafihwuifhuih heruw hewur wheurhuwehurh wheur hwu rhwue iewufh nsjfhwuieru hsudfh
          </DrawerDescription>
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
          <DrawerFooter>
            <DrawerClose asChild>
              <Button>Close</Button>
            </DrawerClose>
            <Button>Save</Button>
          </DrawerFooter>
        </DrawerContent>
    </Drawer>
    ```

**Comment by akiomatic** [comment]
@yuki-92c Thank you for the review.

> Can I ask how to check the scroll feature? In my environment, I cannot check it. I use the code below.

That's because only the content wrapped in the `DrawerDescription` can be scrollable if it's overflowing.
Could you re-check the behavior with the code below and see if it's working for you?

```jsx
      <Drawer>
        <DrawerTrigger asChild>
          <Button>Open Drawer</Button>
        </DrawerTrigger>
        <DrawerContent>
          <DrawerTitle>Login</DrawerTitle>
          <DrawerDescription>
            aaaa hausidfhauisdhfui uahsdfuiasshfuisudf huafihwuifhuih heruw
            hewur wheurhuwehurh wheur hwu rhwue iewufh nsjfhwuieru hsudfh
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
            <Input label="Email" />
          </DrawerDescription>
          <DrawerFooter>
            <DrawerClose asChild>
              <Button>Close</Button>
            </DrawerClose>
            <Button>Save</Button>
          </DrawerFooter>
        </DrawerContent>
      </Drawer>
```

**Comment by yuki-92c** [comment]
> @yuki-92c Thank you for the review.
> 
> > Can I ask how to check the scroll feature? In my environment, I cannot check it. I use the code below.
> 
> That's because only the content wrapped in the `DrawerDescription` can be scrollable if it's overflowing. Could you re-check the behavior with the code below and see if it's working for you?
> 
> ```js
>       <Drawer>
>         <DrawerTrigger asChild>
>           <Button>Open Drawer</Button>
>         </DrawerTrigger>
>         <DrawerContent>
>           <DrawerTitle>Login</DrawerTitle>
>           <DrawerDescription>
>             aaaa hausidfhauisdhfui uahsdfuiasshfuisudf huafihwuifhuih heruw
>             hewur wheurhuwehurh wheur hwu rhwue iewufh nsjfhwuieru hsudfh
>             <Input label="Email" />
>             <Input label="Email" />
>             <Input label="Email" />
>             <Input label="Email" />
>             <Input label="Email" />
>             <Input label="Email" />
>             <Input label="Email" />
>             <Input label="Email" />
>             <Input label="Email" />
>             <Input label="Email" />
>             <Input label="Email" />
>             <Input label="Email" />
>             <Input label="Email" />
>             <Input label="Email" />
>           </DrawerDescription>
>           <DrawerFooter>
>             <DrawerClose asChild>
>               <Button>Close</Button>
>             </DrawerClose>
>             <Button>Save</Button>
>           </DrawerFooter>
>         </DrawerContent>
>       </Drawer>
> ```

Actually, I tried this as well but doesn’t work.

**Review by yuki-92c — APPROVED** [review]
LGTM!

**Pull request merged**
