### PR TITLE
feat: introduce `revalidatePage` as a wrapper for `revalidatePath`

### LINKED ISSUE #285: Implement revalidation wrapper method
## Description

I'll create a `/src/actions/revalidation.ts` file to define a wrapper method to call `revalidatePath` from client components.

## Criteria

- [x] Create `/src/actions/revalidation.ts` file
- [x] Define a `revalidatePage` wrapper function in it
- [x] Describe the usage

### PR DESCRIPTION
**Pull request by akiomatic**
## Overview

I've implemented a wrapper method for `revalidatePath` called `revalidatePage`. This method makes it possible to revalidate a page's cache from server components.

## Changes

- Added `revalidatePage` method in `/src/actions/revalidation`
- Described the function including its usage

## Assignee Checklist:

- [x] The base branch is correct (no accidental merges)
- [x] The branch name follows our branch naming rules
- [x] The PR title follows our PR title rules
- [x] My code follows our coding style
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors in the console

## Reviewer Checklist:

- [ ] Code readability and simplicity
- [ ] Follows best practices and coding standards
- [ ] Understandable and maintainable code

### CODE REVIEW

**Review by Akikaze1119 — APPROVED** [review]
Thank you! LGTM;)

**Review by yuki-92c — APPROVED** [review]
Thank you so much LGTM!

**Review by KaiKoide — APPROVED** [review]
LGTM! Thank you for your work 👍

**Review by HrRn — APPROVED** [review]
LGTM! Thank you✨

**Pull request merged**
