### PR TITLE
feat: add destructive variant to `Input` component

### LINKED ISSUE #90: Add destructive variant to `Input` component

### PR DESCRIPTION
**Pull request by akiomatic**
## Overview
We needed to have a destructive variant for validation fails, as we no longer use the `Form` component from `shadcn/ui`.

## Changes
- Added destructive variant
- Added TSDoc
- Corrected `interface` name to match our standards
- Corrected the type of the `icon` prop
- Set to use parent's 100% width

## Screenshots or videos

https://github.com/Tascurator/tascurator-frontend/assets/124953279/91a75672-7c03-4f73-83cf-95c65bfe4301

## Assignee Checklist:

- [x] The base branch is correct (no accidental merges)
- [x] The branch name follows our branch naming rules
- [x] The PR title follows our PR title rules
- [x] My code follows our coding style
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors in the console

## Reviewer Checklist:

- [ ] Code readability and simplicity
- [ ] Follows best practices and coding standards
- [ ] Understandable and maintainable code

### CODE REVIEW

**Comment by yuki-92c** [comment]
Thanks! I just wanna confirm that the  margin should not be included to the component in this project, right? 
image

**Comment by akiomatic** [comment]
> Thanks! I just wanna confirm that the margin should not be included to the component in this project, right? image

Yes. Thanks for asking. The margins are determined when this component is used, so I didn't include them.

**Comment by akiomatic** [comment]
> Thanks! I just wanna confirm that the margin should not be included to the component in this project, right? image

@yuki-92c Yes. Thanks for asking. The margins are determined when this component is used, so I didn't include them.

**Review by yuki-92c — APPROVED** [review]
Thanks! LGTM:)

**Pull request merged**
